export {default as NavBar } from './NavBar'
export {default as AboutInfo} from './AboutInfo'
export {default as ProjectList} from './ProjectList'
export {default as ConvayBelt} from './ConvayBelt'
export {default as Techstack} from './Techstack'
